export const Images = {
  image1: require('./1.jpg'),
  image2: require('./2.jpg'),
  image3: require('./3.jpg'),
  image4: require('./4.jpg'),
  image5: require('./5.jpg'),
  image6: require('./6.jpg'),
  image7: require('./7.jpg'),
  blueBackground: require('./blue.png'),
  greenBackground: require('./green.png'),
  orangeBackground: require('./orange.png'),
  purpleBackground: require('./purple.png'),
  DailyMix: require('./DailyMix.jpg'),
  Mitraz: require('./Mitraz.jpg'),
  profile_user: require('./profile-user.png'),
  ShaadiMix: require('./ShaadiMix.jpg'),
  TopHits: require('./TopHits.jpg'),
};
