const images = {
  // image1: require('./1.png'),
  // image2: require('./2.png'),
  // image3: require('./3.png'),
  // image4: require('./4.png'),
  // image5: require('./5.png'),
  // image6: require('./6.png'),
  // image7: require('./7.png'),
  // blueBackground: require('./blue.png'),
  // greenBackground: require('./green.png'),
  // orangeBackground: require('./orange.png'),
  // purpleBackground: require('./purple.png'),
  // DailyMix: require('./DailyMix.png'),
  // Mitraz: require('./Mitraz.png'),
  // profile_user: require('./profile-user.png'),
  // ShaadiMix: require('./ShaadiMix.png'),
  // TopHits: require('./TopHits.png'),
};
