export const Icons = {
  add: require('./add.png'),
  apple: require('./apple.png'),
  bell: require('./bell.png'),
  camera: require('./camera.png'),
  camera2: require('./camerax2.png'),
  close: require('./close.png'),
  facebook: require('./facebook.png'),
  favorite: require('./favorite.png'),
  google: require('./google.png'),
  homepage: require('./homepage.png'),
  library: require('./library.png'),
  playButton: require('./play-button.png'),
  plus: require('./plus.png'),
  profile: require('./profile.png'),
  search: require('./search.png'),
  setting: require('./setting.png'),
  recent: require('./recent.png'),
  recents: require('./recents.png'),
  rightArrow: require('./right-arrow.png'),
  settings: require('./setting.png'),
  search_white: require('./search_white.png'),
  spotify: require('./spotify.png'),
  thumbnail: require('./thumbnail.png'),
};
